file,name,complexity
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,AutoReconnect,5
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,AutoReconnect.__init__,4
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,_format_detailed_error,2
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,PyMongoError,2
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,PyMongoError.__init__,2
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,NotPrimaryError,2
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,OperationFailure,2
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,OperationFailure.__init__,2
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,BulkWriteError,2
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,EncryptionError,2
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,_CertificateError,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,PyMongoError.has_error_label,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,PyMongoError._add_error_label,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,PyMongoError._remove_error_label,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,ProtocolError,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,ConnectionFailure,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,NetworkTimeout,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,NotPrimaryError.__init__,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,ServerSelectionTimeoutError,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,ConfigurationError,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,OperationFailure._max_wire_version,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,OperationFailure.code,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,OperationFailure.details,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,CursorNotFound,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,ExecutionTimeout,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,WriteConcernError,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,WriteError,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,WTimeoutError,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,DuplicateKeyError,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,BulkWriteError.__init__,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,BulkWriteError.__reduce__,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,InvalidOperation,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,InvalidName,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,CollectionInvalid,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,InvalidURI,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,DocumentTooLarge,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,EncryptionError.__init__,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,EncryptionError.cause,1
c:/src/pylint-intervention/data/in_the_wild\versions/mongo-python-driver/a0fe7c03af08adde0c893071e1664b43570b9841/after/pymongo_slash_errors.py,_OperationCancelled,1
